In [2]:
import numpy

In [12]:
numpy.loadtxt('inflammation-01.csv', delimiter=',')

array([[ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  1.,  2., ...,  1.,  0.,  1.],
       [ 0.,  1.,  1., ...,  2.,  1.,  1.],
       ..., 
       [ 0.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2.,  0.],
       [ 0.,  0.,  1., ...,  1.,  1.,  0.]])

In [5]:
numpy.loadtxt?

In [14]:
weight_kg = 55

In [15]:
weight_kg

55

In [20]:
weight_lb = 2.2 * weight_kg

In [17]:
weight_lb

121.00000000000001

In [18]:
weight_kg = 70

In [22]:
type(weight_lb)

float

In [23]:
data = numpy.loadtxt('inflammation-01.csv', delimiter=',')

In [24]:
data

array([[ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  1.,  2., ...,  1.,  0.,  1.],
       [ 0.,  1.,  1., ...,  2.,  1.,  1.],
       ..., 
       [ 0.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2.,  0.],
       [ 0.,  0.,  1., ...,  1.,  1.,  0.]])

In [25]:
data.shape

(60, 40)

In [26]:
data.mean()

6.1487499999999997

In [30]:
# average for each patient across all days
data.mean(axis=1).shape

(60,)

In [32]:
data.mean(axis=0).shape

(40,)

In [35]:
data[4, 9]

4.0

In [36]:
data[0, 0]

0.0

In [39]:
data[4, :]

array([  0.,   1.,   1.,   3.,   3.,   1.,   3.,   5.,   2.,   4.,   4.,
         7.,   6.,   5.,   3.,  10.,   8.,  10.,   6.,  17.,   9.,  14.,
         9.,   7.,  13.,   9.,  12.,   6.,   7.,   7.,   9.,   6.,   3.,
         2.,   2.,   4.,   2.,   0.,   1.,   1.])

In [46]:
data[4:11, 7:14].mean(axis=1).std()

0.76305792227918035

Find the minimum of the maximum inflammation across patients for patients 7 through 13 over days 9 through 10.

Each row is a patient, each column is a day.

In [62]:
data[7:14, 9:11].max(axis=1).min()

5.0

In [61]:
numpy.min(numpy.max(data[7:14, 9:11], axis=1))

5.0

In [64]:
double = data * 2

In [65]:
data

array([[ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  1.,  2., ...,  1.,  0.,  1.],
       [ 0.,  1.,  1., ...,  2.,  1.,  1.],
       ..., 
       [ 0.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2.,  0.],
       [ 0.,  0.,  1., ...,  1.,  1.,  0.]])

In [66]:
double

array([[ 0.,  0.,  2., ...,  6.,  0.,  0.],
       [ 0.,  2.,  4., ...,  2.,  0.,  2.],
       [ 0.,  2.,  2., ...,  4.,  2.,  2.],
       ..., 
       [ 0.,  2.,  2., ...,  2.,  2.,  2.],
       [ 0.,  0.,  0., ...,  0.,  4.,  0.],
       [ 0.,  0.,  2., ...,  2.,  2.,  0.]])

In [67]:
triple = double + data

In [69]:
triple * data

array([[  0.,   0.,   3., ...,  27.,   0.,   0.],
       [  0.,   3.,  12., ...,   3.,   0.,   3.],
       [  0.,   3.,   3., ...,  12.,   3.,   3.],
       ..., 
       [  0.,   3.,   3., ...,   3.,   3.,   3.],
       [  0.,   0.,   0., ...,   0.,  12.,   0.],
       [  0.,   0.,   3., ...,   3.,   3.,   0.]])

$3 x^2$

In [73]:
numpy.inner(data, data).shape

(60, 60)

In [74]:
data * 2

array([[ 0.,  0.,  2., ...,  6.,  0.,  0.],
       [ 0.,  2.,  4., ...,  2.,  0.,  2.],
       [ 0.,  2.,  2., ...,  4.,  2.,  2.],
       ..., 
       [ 0.,  2.,  2., ...,  2.,  2.,  2.],
       [ 0.,  0.,  0., ...,  0.,  4.,  0.],
       [ 0.,  0.,  2., ...,  2.,  2.,  0.]])

In [ ]:
import 